version: '3.8'

services:
  byteswar:
    build: .
    container_name: byteswar-game
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - DEBUG=false
      - LOG_LEVEL=info
      - ENABLE_CORS=true
      - CORS_ORIGINS=*
      - ENABLE_CREDENTIALS=false
      - CLIENT_URL=http://byteswar.31.97.151.147.sslip.io
      # Variables para el proxy de Coolify
      - COOLIFY_PROXY=true
      - TRUST_PROXY=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - byteswar-network
    # Configuración adicional para producción
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  byteswar-network:
    driver: bridge 